name: release
on:
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Pull current code version
        run: |
            echo "release_version=Release $(grep -m 1 current_version .bumpversion.cfg | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)" >> $GITHUB_ENV
        id: version
      - name: Generate release tag
        run: |
            BUMPVERSION="$(grep -m 1 current_version .bumpversion.cfg | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)"
            echo "release_tag=v$BUMPVERSION" >> $GITHUB_ENV
        id: tag
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_VERSION }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.release_tag }}
          RELEASE_VERSION: ${{ env.release_version }}
      - name: Build SQL Scripts Assets
        run: make build
      - name: upload oracle artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-oracle.zip
          asset_name: sql-scripts-oracle.zip
          asset_content_type: application/gzip
      - name: upload mssql artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-sqlserver.zip
          asset_name: sql-scripts-sqlserver.zip
          asset_content_type: application/gzip
      - name: upload postgres artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-postgres.zip
          asset_name: sql-scripts-postgres.zip
          asset_content_type: application/zip