name: release
on:
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: version
        run: grep -m 1 current_version .bumpversion.cfg | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3
        id: version
      - name: release
        run: releasePrefix="v"; releaseNumber=$(grep -m 1 current_version .bumpversion.cfg | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3); echo "${releasePrefix}${releaseNumber}"
        id: release
      - name: release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          tag_name: "${{steps.release.outputs.release}}"
          release_name: "${{steps.version.outputs.version}}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build SQL Scripts Assets
        run: make build
      - name: upload oracle artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-oracle.zip
          asset_name: sql-scripts-oracle.zip
          asset_content_type: application/gzip
      - name: upload mssql artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-sqlserver.zip
          asset_name: sql-scripts-sqlserver.zip
          asset_content_type: application/gzip
      - name: upload postgres artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sql-scripts-postgres.zip
          asset_name: sql-scripts-postgres.zip
          asset_content_type: application/zip